GET http://localhost:8080/devops_starter_war_exploded/api/xxx

###
POST http://localhost:8080/api/login
Content-Type: application/json

{"username": "Sebi", "password": "test123"}

###
GET http://localhost:8080/api/users/count

###
GET http://localhost:8080/api/users/find
Content-Type: application/json

{
  "userId": "1"
}
###
GET http://localhost:8080/boat/api/boat/harbour